data_config:
  filter_length: 1024
  hop_length: 256
  mel_fmax: 8000.0
  mel_fmin: 0.0
  n_frames_per_step: 1
  n_mel_channels: 80
  sampling_rate: 22050
  win_length: 1024
decoder_config:
  attention_config:
    attention_dim: 128
    attention_location_kernel_size: 31
    attention_location_n_filters: 32
  attention_rnn_dim: 1024
  decoder_rnn_dim: 1024
  encoder_embedding_dim: 512
  gate_threshold: 0.5
  max_decoder_steps: 2000
  p_attention_dropout: 0.1
  p_decoder_dropout: 0.1
  prenet_dim: 256
encoder_config:
  embedding_dim: 512
  kernel_size: 5
  n_convolutions: 3
postnet_config:
  embedding_dim: 512
  kernel_size: 5
  n_convolutions: 5
symbol_config:
  delimiter: /
  kind: phoneme
  symbols:
  - ɯəj
  - ɤ̆j
  - ʷiə
  - ɤ̆w
  - ɯəw
  - ʷet
  - iəw
  - uəj
  - ʷen
  - tʰw
  - ʷɤ̆
  - ʷiu
  - kwi
  - ŋ͡m
  - k͡p
  - cw
  - jw
  - uə
  - eə
  - bw
  - oj
  - ʷi
  - vw
  - ăw
  - ʈw
  - ʂw
  - aʊ
  - fw
  - ɛu
  - tʰ
  - tʃ
  - ɔɪ
  - xw
  - ʷɤ
  - ɤ̆
  - ŋw
  - ʊə
  - zi
  - ʷă
  - dw
  - eɪ
  - aɪ
  - ew
  - iə
  - ɣw
  - zw
  - ɯj
  - ʷɛ
  - ɯw
  - ɤj
  - 'ɔ:'
  - əʊ
  - ʷa
  - mw
  - 'ɑ:'
  - hw
  - ɔj
  - uj
  - lw
  - ɪə
  - ăj
  - 'u:'
  - aw
  - ɛj
  - iw
  - aj
  - 'ɜ:'
  - kw
  - nw
  - t∫
  - ɲw
  - eo
  - sw
  - tw
  - ʐw
  - iɛ
  - ʷe
  - 'i:'
  - ɯə
  - dʒ
  - ɲ
  - θ
  - ʌ
  - l
  - w
  - '1'
  - ɪ
  - ɯ
  - d
  - ∫
  - p
  - ə
  - u
  - o
  - '3'
  - ɣ
  - '!'
  - ð
  - ʧ
  - '6'
  - ʒ
  - ʐ
  - z
  - v
  - g
  - ă
  - _
  - æ
  - ɤ
  - '2'
  - ʤ
  - i
  - .
  - ɒ
  - b
  - h
  - n
  - ʂ
  - ɔ
  - ɛ
  - k
  - m
  - '5'
  - ' '
  - c
  - j
  - x
  - ʈ
  - ','
  - '4'
  - ʊ
  - s
  - ŋ
  - a
  - ʃ
  - '?'
  - r
  - ':'
  - η
  - f
  - ;
  - e
  - t
  - ''''
  symbols_embedding_dim: 512
train_config:
  batch_size: 30
  device: cuda:0
  drop_frame_rate: 0.2
  eval_steps: 2000
  learning_rate: 0.0005
  log_dir: output/
  num_iters: 200000
  precomputed_mels: mels/
  pretrained_md5: 47727ea0a3df6c966f445c8502943802
  pretrained_url: 1sdo0mwL7pEtXFp_EZiLE2H3DTNDo2Yb_
  test_files: test_files.txt
  train_files: train_files.txt
  warmup_steps: 50000
